blank_issues_enabled: true
contact_links:
  - name: Community Discussions & Ideas
    url: https://github.com/candraalief/hp-14s-fq2003au-easyeffects/discussions
    about: Ask questions, share audio clips, or discuss tuning ideas with other HP Linux users!
